### ISSUE TITLE
404 CSS when using the Bulk Translate feature with Polylang Pro

### ISSUE THREAD

**Issue by Elisa3232** [creame/connect-polylang-elementor#13]
Following an issue with CSS Elementor alighted with a common customer, we would like to submit the situation for a possible enhancement with Polylang Connect for Elementor.

## Prerequisites
Elementor 3.13.4
Polylang Connect for Elementor 2.4.2
Polylang Pro 3.4.2
Theme Twenty-Twenty-Three 1.1

## Steps to reproduce the issue (See video also)
1. Create a new page “AA Sample page” in your Main language (Example EN) and Edit with Elementor
2. Add a Text block with Elementor and custom CSS (Color+Font)
3. Save your page
4. Go back to your page list
5. Using the Bulk Translate feature, translate your page “AA Sample page” choosing the option “Synchronize translations in selected languages with the original items” into a secondary language. 
Video : [https://www.loom.com/share/50fab319be4a4209952bc26455f0b9de]

## Expected behavior

I was expecting that the text Block would maintain the original CSS from the Main language BUT when I follow those steps, I see missing CSS (404) in the translated version.

Workaround : Manually editing and saving each of the pages correct the behavior but loses the interest of the bulk action.

## Additional information : 
Custom CSS is stored in a "post-ID.css" and Polylang's synchronization tool is not able to synchronize the data of this kind of files. Polylang's tool synchronizes the data stored in the database only. It means that the custom CSS is not copied or synchronized into the new translations. 

## Possible solution : 
Possibly hooking on "pll_created_sync_post" documented on wp-content/plugins/polylang-pro/modules/sync-post/sync-post-model.php:173

**Comment by DevinFredericks** [comment]
Happy to see this issue was already reported and resolved. Nice work! We're running the latest Polylang Pro andConnect Polylang for Elementor plugin but we were still experiencing the issue where the styles were broken on synchronized translation pages. We realized that our CSS Print Method in Eelementor > Advanced was set to internal Embedding, rather than the default External File. Once this was changed back to External File, the issue was resolved, as per @pacotole 's confirmation. Perhaps this might be helpful for anyone who runs into the same issue. Thanks again!
